// Generated by CoffeeScript 2.4.1
(function() {
  var height, path, svg, width, xym;

  width = 960;

  height = 700;

  svg = d3.select('#map-holder').append('svg').attr('width', width).attr('height', height);

  xym = d3.geo.albers();

  path = d3.geo.path().projection(xym);

  xym.origin([134, 25]);

  xym.translate([350, 745]);

  xym.parallels([24.6, 43.6]);

  xym.scale(1980);

  d3.json('nihon.geo.json', function(data) {
    svg.selectAll('path').data(data.features).enter().append('path').attr('d', path).style('fill', function() {
      return '#44aaee';
    }).on('mouseover', function(e) {
      d3.select(this).style('fill', '#5522aa');
    }).on('mouseout', function(e) {
      d3.select(this).style('fill', '#44aaee');
    });
  });

}).call(this);

//# sourceMappingURL=brain.js.map
